import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ChatBubble from '../components/ChatBubble';
import { IoSend } from 'react-icons/io5';

export type Message = {
  text: string;
  name: string;
  createdAt: string;
};

const defaultMessages: Message[] = [
  {
    text: 'Hey Travis! Would you like to go out for a coffee?',
    name: 'others',
    createdAt: '20:21',
  },
  {
    text: 'Sure! At 11:00 am?',
    name: 'me',
    createdAt: '20:22',
  },
  {
    text: "That's too early! How about at noon?",
    name: 'others',
    createdAt: '20:22',
  },
  {
    text: 'That sounds good as well. Where should we meet?',
    name: 'me',
    createdAt: '20:23',
  },
  {
    text: 'Meet me at the hardware store on 21 Duck Street.',
    name: 'others',
    createdAt: '20:23',
  },
  {
    text: "Sounds good. I'll bring my friend with me as well!",
    name: 'me',
    createdAt: '20:24',
  },
  {
    text: 'Which one? The developer or the designer?',
    name: 'others',
    createdAt: '20:24',
  },
  {
    text: 'The developer. You remember Tony, right?',
    name: 'me',
    createdAt: '20:24',
  },
  {
    text: "Yeah! Tony's a great guy!",
    name: 'others',
    createdAt: '20:25',
  },
  {
    text: 'Indeed he is! Alright, see you later 👋!',
    name: 'me',
    createdAt: '20:25',
  },
];

const Home: NextPage = () => {
  const [messages, setMessages] = React.useState<Message[]>(defaultMessages);
  const endOfChatRef = React.useRef<HTMLDivElement | null>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.chat_box}>
          {messages?.map((message, index) => (
            <ChatBubble key={index} message={message} />
          ))}
          <div ref={endOfChatRef}></div>
        </div>
        <div className={styles.input_section}>
          <form autoComplete='off'>
            <div className={styles.input_container}>
              <input
                type='text'
                placeholder='Type your message'
                className={styles.input_box}
              />
              <button className={styles.send_button}>
                <IoSend />
              </button>
            </div>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
